---
title: "Reader"
format: html
author:
  - name: Daniel Antal
    orcid: 0000-0003-1689-0557
toc: true
lang: en-GB
date: today
papersize: A4
subject: Music business
keywords:
  - Indicators
  - Triple transition
  - Open Music Europe
  - Bibliography
editor: visual
bibliography: 
  - bib/ratings.bib
  - bib/tripletransition.bib
---

## tripletransition.bib

`bib/tripletransition.bib`

-   Towards a green, digital and resilient economy: our European Growth Model [@commission_towards_green_digital_resilient_2022]

-   A new era for Europe: how the European Union can make the most of its pandemic recovery, pursue sustainable growth, and promote global stability [@european_commission_new_era_2022]

-   Building a stronger Single Market for Europe's recovery. Annual Single Market Report 2021 [@european_commission_annual_single_market_report_2021]

-   The Three MuskEUteers [@caro-gonzalez_three_muskeuteers_2023]

-   Green Economy Project Management Cases [@krasniqi_green_project_management_2018]

-   Slovakia's Vision and Development Strategy 2030 - a long-term strategy for sustainable development [@slovak_sdg_strategy_2020]

Triple transition [used to be](https://link.springer.com/chapter/10.1007/978-3-642-52404-2_2) a buzzword for a different transition.

### Digitisation

-   Regulation (EU) 2021/694 of the European Parliament and of the Council of 29 April 2021 establishing the Digital Europe Programme [@eu_regulation_2021-694]

-   2030 Digital Transformation Strategy for Slovakia [@2030_digital_transformation_slovakia_en_2019; 2030_digital_transformation_slovakia_sk_2019]

-   Digital Economy and Society Index (DESI), country report on Slovakia [@desi_slovakia_2022]

### Slovak policy documents
`bib/slovakia.bib`

-   Stratégia kultúry a kreatívneho priemyslu Slovenskej republiky 2030. \[Strategy of the cultural and creative industries of the Slovak Republic 2030.\] [@slovak_cci_strategy_2023]
-   2030 Digital Transformation Strategy for Slovakia [@2030_digital_transformation_slovakia_en_2019; 2030_digital_transformation_slovakia_sk_2019]
-   Slovakia's Vision and Development Strategy 2030 - a long-term strategy for sustainable development [@slovak_sdg_strategy_2020]
